Ad 53 explore alice donation contracts
alice-si/contracts pull request #1
Opened 2018-08-06 09:45 UTC by alexAlice

2018-08-08 11:50 UTC, jakub-wojciechowski requested changes

2018-08-08 11:50 UTC, jakub-wojciechowski commented on contracts/ContractProvider.sol
> +pragma solidity ^0.4.22;
Why cannot we update to 0.4.24?

2018-08-08 11:50 UTC, jakub-wojciechowski commented on quarantine/integration/single-donation.js
> +  var val = accounts[3];
Does it work, you refer to this variable as "validator" later on.

2018-08-08 11:50 UTC, jakub-wojciechowski commented on test/helper.js
> +  prepare: function () {
Could you please remove the prepare method and rename the module to test-setup or test-preparation, so the syntax is more concise?

2018-08-08 14:32 UTC, alexAlice commented on quarantine/integration/single-donation.js
> +  var val = accounts[3];
It doesn't work. I haven't noticed it because I have not run tests from qurantine :)

2018-08-09 07:18 UTC, jakub-wojciechowski commented
Please update the amount of gas because after update of OpenZeppelin the base contract is more expensive and the deployment is broken: 

in app.js change to:
TokenContract = await AliceToken.new({from: aliceAccount, gas: 3000000});

2018-08-09 10:12 UTC, jakub-wojciechowski approved these changes

2018-08-09 10:56 UTC, merged