DigitalGBPToken and successful tests
alice-si/contracts pull request #4
Opened 2018-09-03 17:44 UTC by DhenPadilla

- Added a separate tests file for the DigitalGBPToken.

- 5 Tests, All pass

- 1 test checking whether an error is thrown when burning too many tokens.

2018-09-03 17:46 UTC, DhenPadilla commented on test/digital_g_b_p_token.js
> +  const ERROR_MSG = 'VM Exception while processing transaction: revert';
Removed this, also

2018-09-05 13:02 UTC, jakub-wojciechowski requested changes
Great job, please take a look at the comments.

2018-09-05 13:02 UTC, jakub-wojciechowski commented on test/digital_g_b_p_token.js
> +  const ERROR_MSG = 'VM Exception while processing transaction: revert';
You can use .shouldBeReverted assertion

2018-09-05 13:02 UTC, jakub-wojciechowski commented on test/digital_g_b_p_token.js
> +    it('Reject Burn when burning more than total supply', async function() {
You can also use the .shouldBeReverted assertion to check if an error has been throwed

2018-09-05 13:02 UTC, jakub-wojciechowski commented on test/digital_g_b_p_token.js
> +    it('Reject Burn when burning more than total supply', async function() {
Please make a space (empty line) between functions. It easier to read that way (and looks nicer too ;))

2018-09-05 13:02 UTC, jakub-wojciechowski commented on test/digital_g_b_p_token.js
> +      assert.equal(name, _name, 'Name is correct');
We tend to use chai assertions in all of the other tests, imho is more readable.

2018-09-05 13:02 UTC, jakub-wojciechowski commented on test/digital_g_b_p_token.js
> +    it('Reject Burn when burning more than total supply', async function() {
I'll also test a more narrow constraint with burning more than the account balance

2018-09-05 13:02 UTC, jakub-wojciechowski commented on test/digital_g_b_p_token.js
> +    it('Reject Burn when burning more than total supply', async function() {
It'll be also good to test if minting a burning could be called only by the owner.

2018-10-09 05:31 UTC, merged